env:
  global:
    PYTHON_CONFIGURE_OPTS="--enable-shared"

matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      env: PYINSTALLER_VERSION=3.3.1
    - os: linux
      language: python
      python: 2.7
      env: PYINSTALLER_VERSION=develop
    - os: linux
      language: python
      python: 3.6
      env: PYINSTALLER_VERSION=3.3.1
    - os: linux
      language: python
      python: 3.6
      env: PYINSTALLER_VERSION=develop
    - os: osx
      language: c
      env: PYENV_VERSION=2.7.14 PYINSTALLER_VERSION=3.3.1
    - os: osx
      language: c
      env: PYENV_VERSION=2.7.14 PYINSTALLER_VERSION=develop
    - os: osx
      language: c
      env: PYENV_VERSION=3.6.3 PYINSTALLER_VERSION=3.3.1
    - os: osx
      language: c
      env: PYENV_VERSION=3.6.3 PYINSTALLER_VERSION=develop


before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi

install:
  - pip install -r requirements.txt
  - ./install-pyinstaller.sh

script:
  - ./test.sh
