os:
  - linux
  - osx

language:
  - python
  - c

python:
  - 2.7
  - 3.6

env:
  global:
    - PYINSTALLER_DEVELOP=https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  matrix:
    - PYTHON_VERSION=2.7 PYINSTALLER_VERSION=3.3.1
    - PYTHON_VERSION=2.7 PYINSTALLER_VERSION=$PYINSTALLER_DEVELOP
    - PYTHON_VERSION=3.6 PYINSTALLER_VERSION=3.3.1
    - PYTHON_VERSION=3.6 PYINSTALLER_VERSION=$PYINSTALLER_DEVELOP

matrix:
  exclude:
    - os: osx
      language: python
    - os: linux
      language: c


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHON_VERSION ; done
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global $PYTHON_VERSION ; done

install:
  - pip install -r requirements.txt
  - pip install pyinstaller=$PYINSTALLER_VERSION

script:
  - ./test.sh
