matrix:
  include:
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.6
    - os: osx
      env: PYTHON_VERSION=2.7
    - os: osx
      env: PYTHON_VERSION=3.6


before_install:
  - .travis/bootstrap-osx.sh

install:
  - pip install -r requirements.txt

script:
  - ./test.sh
