matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      env: PYINSTALLER_VERSION=3.3.1
    - os: linux
      language: python
      python: 2.7
      env: PYINSTALLER_VERSION=develop
    - os: linux
      language: python
      python: 3.6
      env: PYINSTALLER_VERSION=3.3.1
    - os: linux
      language: python
      python: 3.6
      env: PYINSTALLER_VERSION=develop
    - os: osx
      language: c
      env: PYTHON_VERSION=2.7 PYINSTALLER_VERSION=3.3.1
    - os: osx
      language: c
      env: PYTHON_VERSION=2.7 PYINSTALLER_VERSION=develop
    - os: osx
      language: c
      env: PYTHON_VERSION=3.6 PYINSTALLER_VERSION=3.3.1
    - os: osx
      language: c
      env: PYTHON_VERSION=3.6 PYINSTALLER_VERSION=develop


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHON_VERSION ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global $PYTHON_VERSION ; fi

install:
  - pip install -r requirements.txt
  - .travis/install-pyinstaller.sh

script:
  - ./test.sh
